 
import Container from "./_components/container/container";
import Header from "./_components/header/header";
import "./globals.css";
 import { Inter } from 'next/font/google'
 
 const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={inter.className}  >

        <Container>
              <Header />
        </Container>
        {children}
      </body>
    </html>
  );
}
